import Head from 'next/head';
import Link from 'next/link';
import Footer from '../components/Footer';
import styles from '../styles/Home.module.css';

/** Home */
export default () => (
  <div className={styles.container}>
    <Head>
      <title>Streamswap</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>Streamswap</h1>

      <p>
        Continuous exchange of{' '}
        <a href="https://superfluid.finance" target="_blank" rel="noopener">
          Superfliud
        </a>{' '}
        streams
      </p>

      <div className={styles.grid}>
        <Link href="/exchange">
          <a className={styles.card}>
            <h2>Exchange &rarr;</h2>
            <p>Start exchanging super tokens now!</p>
          </a>
        </Link>

        <a href="" className={styles.card}>
          <h2>Documentation &rarr;</h2>
          <p>Learn about the inner workings of Streamswap.</p>
        </a>
      </div>
    </main>

    { Footer() }
  </div>
);
